# Enable CSRF protection for forms
framework:
    form:
        csrf_protection:
            token_id: submit

    # Configuration CSRF standard - sans utiliser stateless_token_ids pour l'authentification
    csrf_protection: ~
